services:
  elora-chat:
    build: .
    ports:
      - "8080:8080"
    environment:
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
      - TWITCH_REDIRECT_URL=${TWITCH_REDIRECT_URL}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - PORT=${PORT}
      - DEPLOYED_URL=${DEPLOYED_URL}
    develop:
      watch:
        - action: rebuild
          path: ./src/frontend
          target: /app
        - action: sync+restart
          path: ./python
          target: /app/python
        - action: rebuild
          path: ./src/backend
          target: /app
          include: "**/*.go"
